In [1]:
import numpy as np
import pandas as pd
from kaggle_jpx_package import ScoringService
# import sys
# sys.path.append('/Users/mogitaketo/code/kaggle/jpx/src/kaggle_jpx_package')
# from processor import ScoringService

In [2]:
ss = ScoringService()
# ss.get_dataset()
df_merge = ss.get_df_merge(debug=True)

In [3]:
df_merge.tail()

,RowId,Date,SecuritiesCode,Open,High,Low,Close,Volume,AdjustmentFactor,ExpectedDividend,...,d_vol,range,atr_1,atr_5,atr_10,atr_20,atr_40,atr_60,atr_100,d_atr
102001,20220221_1332,2022-02-21,1332,552.0,553.0,547.0,550.0,1260300,1.0,NaN,...,0.569724,0.023214,0.023214,0.022114,0.025929,0.023836,0.021212,0.022726,0.024244,0.973914
104001,20220222_1332,2022-02-22,1332,543.0,543.0,534.0,542.0,1651100,1.0,NaN,...,0.740204,0.029091,0.029091,0.023600,0.024779,0.024259,0.021707,0.022961,0.024413,1.199193
106001,20220224_1332,2022-02-24,1332,540.0,540.0,526.0,533.0,3108600,1.0,NaN,...,1.335958,0.029520,0.029520,0.026637,0.023116,0.024722,0.021981,0.023257,0.024513,1.194097
108001,20220225_1332,2022-02-25,1332,528.0,533.0,525.0,532.0,2349400,1.0,NaN,...,0.980391,0.015009,0.015009,0.024621,0.022591,0.024919,0.022126,0.023085,0.024404,0.602331
110001,20220228_1332,2022-02-28,1332,531.0,545.0,531.0,544.0,2437900,1.0,NaN,...,1.006870,0.026316,0.026316,0.024630,0.022859,0.024851,0.022508,0.023011,0.024484,1.058949

In [4]:
%debug

ERROR:root:No traceback has been produced, nothing to debug.

## todo
- [x] pricesとprices_supを結合して使えるようにする 5/4 
- [x] classmethodじゃなくてinstance methodにかえる
- [ ] テスト組む