In [1]:
import numpy as np
import pandas as pd
import sys
sys.path.append('/Users/mogitaketo/code/kaggle/jpx/src')

In [2]:
from processor import ScoringService as SS
SS.get_dataset()
df_merge = SS.get_df_merge(debug=True)

/Users/mogitaketo/code/kaggle/jpx/src/processor.py:44: DtypeWarning: Columns (14,15,16,17,18,19,42,44) have mixed types. Specify dtype option on import or set low_memory=False.
  cls.dfs[key] = pd.read_csv(value)
/Users/mogitaketo/code/kaggle/jpx/src/processor.py:44: DtypeWarning: Columns (7,8,9,10) have mixed types. Specify dtype option on import or set low_memory=False.
  cls.dfs[key] = pd.read_csv(value)
/Users/mogitaketo/code/kaggle/jpx/src/processor.py:44: DtypeWarning: Columns (7,8,9,10) have mixed types. Specify dtype option on import or set low_memory=False.
  cls.dfs[key] = pd.read_csv(value)

In [17]:
df_merge.tail()

,RowId,Date,SecuritiesCode,Open,High,Low,Close,Volume,AdjustmentFactor,ExpectedDividend,...,d_vol,range,atr_1,atr_5,atr_10,atr_20,atr_40,atr_60,atr_100,d_atr
2322532,20211129_1332,2021-11-29,1332,579.0,579.0,567.0,567.0,1607200,1.0,NaN,...,0.867863,0.030769,0.030769,0.021303,0.020124,0.026747,0.026693,0.024283,0.024010,1.150376
2324532,20211130_1332,2021-11-30,1332,580.0,590.0,573.0,573.0,2732300,1.0,NaN,...,1.420015,0.040564,0.040564,0.024678,0.023376,0.027545,0.026786,0.024629,0.024110,1.472682
2326532,20211201_1332,2021-12-01,1332,568.0,578.0,568.0,574.0,1661300,1.0,NaN,...,0.865121,0.017452,0.017452,0.025173,0.023032,0.026640,0.026905,0.024699,0.024154,0.655112
2328532,20211202_1332,2021-12-02,1332,566.0,577.0,565.0,573.0,1525800,1.0,NaN,...,0.786606,0.020906,0.020906,0.026997,0.022214,0.026699,0.026717,0.024470,0.024270,0.783032
2330532,20211203_1332,2021-12-03,1332,579.0,585.0,570.0,585.0,1195500,1.0,NaN,...,0.634499,0.026178,0.026178,0.027174,0.022510,0.026313,0.026644,0.024693,0.024292,0.994882

In [19]:
SS.dfs.keys()

dict_keys(['prices', 'prices_sec', 'fins', 'options', 'trades', 'prices_sup', 'prices_sec_sup', 'fins_sup', 'options_sup', 'trades_sup', 'stock_list', 'options_spec', 'stock_fin_spec', 'stock_list_spec', 'stock_price_spec', 'trades_spec'])

In [21]:
pd.concat([SS.dfs['prices'], SS.dfs['prices_sup']])

,RowId,Date,SecuritiesCode,Open,High,Low,Close,Volume,AdjustmentFactor,ExpectedDividend,SupervisionFlag,Target
0,20170104_1301,2017-01-04,1301,2734.0,2755.0,2730.0,2742.0,31400,1.0,NaN,False,0.000730
1,20170104_1332,2017-01-04,1332,568.0,576.0,563.0,571.0,2798500,1.0,NaN,False,0.012324
2,20170104_1333,2017-01-04,1333,3150.0,3210.0,3140.0,3210.0,270800,1.0,NaN,False,0.006154
3,20170104_1376,2017-01-04,1376,1510.0,1550.0,1510.0,1550.0,11300,1.0,NaN,False,0.011053
4,20170104_1377,2017-01-04,1377,3270.0,3350.0,3270.0,3330.0,150800,1.0,NaN,False,0.003026
...,...,...,...,...,...,...,...,...,...,...,...,...
111995,20220228_9990,2022-02-28,9990,511.0,518.0,509.0,516.0,120600,1.0,NaN,False,-0.013592
111996,20220228_9991,2022-02-28,9991,823.0,825.0,814.0,822.0,16200,1.0,NaN,False,-0.020581
111997,20220228_9993,2022-02-28,9993,1600.0,1622.0,1600.0,1600.0,4000,1.0,NaN,False,0.005762
111998,20220228_9994,2022-02-28,9994,2568.0,2568.0,2540.0,2565.0,9000,1.0,NaN,False,-0.002341
111999,20220228_9997,2022-02-28,9997,731.0,737.0,726.0,734.0,288100,1.0,NaN,False,-0.030014

## todo
- pricesとprices_supを結合して使えるようにする